# Generated by Django 5.2.4 on 2025-08-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message_property_rental_transaction_useridentity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentity',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer')], default='buyer', max_length=10),
        ),
    ]
