# Generated by Django 5.2.4 on 2025-08-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
