# Generated by Django 5.2.4 on 2025-08-10 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
