# Generated by Django 5.2.4 on 2025-08-10 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('username', 'property')},
        ),
    ]
