# Generated by Django 5.2.4 on 2025-08-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL', max_length=500, null=True),
        ),
    ]
