# Generated by Django 5.2.4 on 2025-08-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_property_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=150)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=20)),
                ('property_name', models.CharField(max_length=200)),
                ('seller_username', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
