# Generated by Django 5.2.4 on 2025-08-14 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_callback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callback',
            name='property_name',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='seller_username',
        ),
        migrations.AddField(
            model_name='callback',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.property'),
        ),
        migrations.AddField(
            model_name='callback',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.useridentity'),
        ),
    ]
