# Generated by Django 5.2.4 on 2025-08-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_callback_property_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='calledornot',
            field=models.BooleanField(default=False),
        ),
    ]
