# Generated by Django 5.2.4 on 2025-08-16 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_callback_calledornot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callback',
            old_name='calledornot',
            new_name='called',
        ),
    ]
