# Generated by Django 5.2.4 on 2025-08-17 10:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_calledornot_callback_called'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='is_rented',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='lease_duration_months',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rent_per_month',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rent_start_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rented_by',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='security_deposit',
        ),
        migrations.AddField(
            model_name='rental',
            name='rented_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='tenant_agreement',
            field=models.FileField(blank=True, null=True, upload_to='agreements/'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='api.property'),
        ),
    ]
