# Generated by Django 5.2.4 on 2025-08-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_rental_is_rented_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='property',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
