# Generated by Django 5.2.4 on 2025-08-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='status',
        ),
    ]
