# Generated by Django 5.2.4 on 2025-08-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_agreement_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
